### ISSUE TITLE
Virtualbox VM download

### ISSUE THREAD

**Issue by hmallepally** [seeker89/chaos-engineering-book#19]
I was unable to install ubuntu into virtual box, for some reason it keeps restarting the process. 

Per your book instructions, I was supposed to download the VB image already, can you please help me with instructions? the source code download doesn't include VM image itself.

**Comment by seeker89** [comment]
Hey,

Please make sure you downloaded the right files. For example, for this release https://github.com/seeker89/chaos-engineering-book/releases/tag/focal.rc1 you need to download the right files from the `assets` section, like so:

![image](https://user-images.githubusercontent.com/480314/95686646-11e54d80-0bf7-11eb-8fd7-dc6a53250628.png)


Feel free to reopen if you still run into trouble Thanks!
