### ISSUE TITLE
VALIDATE cgroup2 in VM on Win 10 x64

### ISSUE THREAD

**Issue by misstickles** [seeker89/chaos-engineering-book#21]
Hi,

I am on Windows 10, 20H2.  I have downloaded all files for the VM, (RC1), https://github.com/seeker89/chaos-engineering-book/releases/tag/focal.rc1 and ensured the SHAs are matching.

I have imported the "Appliance" and set up VirtualBox as described;  (per some answers on the internet) Hyper-V is OFF (I run Docker, but on WSL).  I have run Ubuntu VMs in the past, without issue (and my Win95 one is currently quite happy 🤣  ).

However, I am unable to get past `*** VALIDATE cgroup2 ***` message during boot.  Do you know what I've missed??  There are some logs, but I don't want to pollute this message with tonnes of them...

Thanks.

![image](https://user-images.githubusercontent.com/18216511/112872166-f47a4200-90b7-11eb-9cc8-5105a39ccb56.png)

**Comment by seeker89** [comment]
Thanks for the issue. Would any of this https://forums.virtualbox.org/viewtopic.php?f=6&t=97142 help?
I don't have a windows 10 machine at hand, but I can try to get something.

**Comment by seeker89** [comment]
Actually, that's probably not relevant. Which version of VirtualBox are you using?

**Comment by misstickles** [comment]
It is a bit relevent!  I had the setup defined in that particular post, but it links to https://forums.virtualbox.org/viewtopic.php?f=1&t=62339.  I tried the 2nd comment step 2 (3 already applied), which had no affect.  The 3rd comment, says to also switch off  `Virtual Machine Platform` and `Windows Hypervisor Platform` (all others already applied) - this DID make it load correctly.

However, now I can't use WSL or Docker, which is a no-go for me...

VirtualBox is v6.1 (6.1.18 r142142 (Qt5.6.2))

**Comment by misstickles** [comment]
After a heap of time trying (most) options in VirtualBox - VMWare seems to work out-the-box (no changes at all).  Obviously, I'm only on chapter 2 (!) so I will let you know if I have any problems via VMWare.

**Comment by seeker89** [comment]
Awesome!

It's interesting. I've used VirtualBox on mac for years and I've never had any problems, but people do seem to have trouble on Windows pretty regularly.
