### ISSUE TITLE
(PDF) Pg 65 - footnote at the bottom of the page is incorrectly linked

### ISSUE THREAD

**Issue by MalcolmAnderson** [seeker89/chaos-engineering-book#28]
The footnote at the bottom of page 65 in the PDF is trying to reach
https://mng.bz/A0y7.%20Isn%E2%80%99t%20that%20amazing
which gives me the following error
"Sorry, you're not authorized to view this page."

After looking at it, I see that the link should have been 
https://mng.bz/A0y7
Which correctly links to the page
https://github.com/iovisor/bcc/blob/0e63c5c1ad267281f8d0b652eaf87dd494ddba04/tools/oomkill.py#L38

To be honest, I didn't understand what I was looking at on that page.
I kind of felt like I was looking at a great piece of art, but was too uneducated to understand the beauty of what I was looking at.
It looks like a pretty clean piece of C code and I could mostly follow along with it.  

I appreciate that this code is tight, but what should my take away be?
My biggest takeaway is, "Huh, this code is pretty approachable, maybe I should read more linux system diagnostic code."

**Comment by seeker89** [comment]
If that was your key takeway, I'm pretty happy with how it panned out :)

Would you be so kind as to raise the broken link as a comment in https://livebook.manning.com/book/chaos-engineering/discussion ? The publisher will be able to fix it.

Many thanks!

**Comment by MalcolmAnderson** [comment]
Added the comment to the publisher's page (it's still wrong on their site)
Do we leave the issue open until they fix the issue on the site?

**Comment by seeker89** [comment]
Thanks so much. It's their responsibility to fix it, so let's close the issue.
